### ISSUE TITLE
Option to swith the main pdf background to white.

### ISSUE THREAD

**Issue by CharlesChiuGit** [ThomasFKJorna/zotero-night#1]
Would it be possible to just swith the main pdf background to white while maintaining the side panels in the night theme?
Some of the pictures blend in too well with the dark background.

**Comment by CharlesChiuGit** [comment]
Or maybe this funciton is already in the roadmap?

**Comment by ThomasFKJorna** [comment]
Yeah I do want to include that but is probably a good one to do first!

Do you a think it would be better to have this as a separate toggle from "complete" night mode, and/or to have this be toggle able on a per pdf basis? The way the extension works means that it's easier to do it per pdf rather than have a global toggle, but a global setting can work as well

**Comment by CharlesChiuGit** [comment]
Wow, that's interesting! Never thought that plugins can allow such fine-grind controls!

In my case, I would probably only use the global toggle to switch from "complete night mode" and "partial night mode", since most of my pdfs are just less than 10 pages and with lots of pictures. It would take me too much efforts to switch each pdf's settings.

But for someone reading both long pdfs and short pdfs, I think it would be nice to have a more fine-grind control over "complete night mode" and "partial night mode" on each pdfs.

**Comment by ThomasFKJorna** [comment]
I just added this! You can set a default in the settings, or switch between modes using the toggle on the toolbar.
I also added one more mode, which blends in with the background.

Hope you like it! I still want to add some possibility for Night "remembering" which mode the pdf is supposed to be in, but this is good enough for me for now.

https://user-images.githubusercontent.com/21983833/164005237-b849c58f-b9cf-4570-ae55-be9206fb3731.mov

**Comment by ThomasFKJorna** [comment]
I will mark this as closed, if this does not do what you want feel free to reopen it!

**Comment by CharlesChiuGit** [comment]
That's exactly what I need! Really appreciate your great work! Thanks you!

**Comment by ThomasFKJorna** [comment]
The latest version also has proper loading of the styles and a global toggle button, check it out!

**Comment by CharlesChiuGit** [comment]
For some reason, the latest version isn't rendering the left panel and the Note(on the right panel) to night theme. Retreat to 0.1.2 seems the best solution for me.

**Comment by CharlesChiuGit** [comment]
Sorry, restart zotero again did the trick.
