### ISSUE TITLE
Zotero Night dissappears after closing and opening Zotero on MacOS

### ISSUE THREAD

**Issue by shaneleeliar** [ThomasFKJorna/zotero-night#15]
night for Zotero doesnt get along with version 6.0.6.\
every time i minomize the app and turn up, the UI turn into day mode.
its normal after i re-install the add-on.
 macine -Mac

**Comment by ThomasFKJorna** [comment]
Im not sure I understand what you mean? After minimizing Zotero and reopening it, the dark theme is gone?

This does not happen for me on 12.3, what version of MacOS are you on?

**Comment by RamonMeffert** [comment]
This happens to me also, but only when closing the main window. The UI is reset to day mode, and the theme toggle in the upper right corner also disappears. Restarting the application fixes both issues. I'm on macOS 12.3.1 with Zotero 6.0.6 and v0.2.2 of the add-on.

**Comment by ThomasFKJorna** [comment]
Yeah I can indeed reproduce this, I'm not used to doing this in MacOS myself so I hadn't even noticed yet! I wonder if Zotero reloads all styles when it reopens, that would be really annoying

**Comment by ThomasFKJorna** [comment]
This should be fixed now!

**Comment by WMAM** [comment]
I think I am having the same problem on Windows. 

On Zotero, I run the command to update the plugins (via Tools>Add-ons) and the main DB window turns to day mode (PDF tabs seems to work fine) and the theme toggle in the upper right corner disappeared. I have to restart the computer to bring back the dark mode. Moreover, the add-ons windows does not appear.

Also, here in github it appears that the latest version is 0.2.5, but I can't update from 0.2.2.

**Comment by ThomasFKJorna** [comment]
I have no idea why it would block betterBibtex, but the update issue should now ave been resolved

**Comment by ThomasFKJorna** [comment]
I'll close this issue and track it in #21
