### ISSUE TITLE
It seems to cause icon dislocation

### ISSUE THREAD

**Issue by liliadamth** [ThomasFKJorna/zotero-night#17]
### It seems to cause icon dislocation. ### 
After installation, there may be such a display error in light mode. Night mode is great！

![屏幕截图 2022-04-29 101256](https://user-images.githubusercontent.com/75127969/165876263-a7213144-75a9-40ad-8547-9fe5e50057fb.png)
![屏幕截图 2022-04-29 101313](https://user-images.githubusercontent.com/75127969/165876266-57c099da-b2a6-41ee-88e8-a7f7c6c6a690.png)

**Comment by MSBack** [comment]
I had this issue before installing the plugin.

**Comment by liliadamth** [comment]
> I had this issue before installing the plugin.

oh, thanks, it was my misjudgment. It might not be this plugin's fault.
