### ISSUE TITLE
Menubar is white

### ISSUE THREAD

**Issue by Rosmaninho** [ThomasFKJorna/zotero-night#19]
Hello. In Windows the menubar shows with a white background:
![image](https://user-images.githubusercontent.com/42737369/165919793-bfcf5a09-ea8b-4147-91b8-fe6ae00523f7.png)

**Comment by ThomasFKJorna** [comment]
Closed in favor of #18

**Comment by ThomasFKJorna** [comment]
Oh wait, you probably know this since you made the other theme! Which selector is this? I'm unable to find it as I'm on MacOS

**Comment by ThomasFKJorna** [comment]
Also, how do you feel about the scrollbars? They look absolutely terrible on Windows I feel. The best I could do is slightly hide them (like make only 20% of it visible), which is not suuuper accessible but works.

Otherwise I could try and create my own scrollbars, which is always kinda tricky

**Comment by Rosmaninho** [comment]
Should be #navigator-toolbox. Not sure if there's something else conflicting with this ID.
You can't run Windows on Parallels or something? That way you could check your changes on Windows...

The toolbars look terrible. Windows has dark mode scrollbars that apps that support dark mode can use. But I don't know how to call them. I think creating scrollbars is a lot of wasted time. You can use it to better polish your extension currently.

**Comment by ThomasFKJorna** [comment]
Latest patch might fix the toolbar, could you test it?
