### ISSUE TITLE
Night mode disappears when you close and reopen zotero window on mac

### ISSUE THREAD

**Issue by skymagician** [ThomasFKJorna/zotero-night#20]
Zotero 6.06
Night for Zotero 0.2.2
MacOS Monterey 12.3.1
macbook air m1

Steps to reproduce：
1. open zotero
2. close the zotero window (not quit)
3. reopen zotero window
4. night mode disappers

**Comment by ThomasFKJorna** [comment]
Thanks, this is indeed a problem i can reproduce, I will close this in favor of #15
