### ISSUE TITLE
Pdf dark mode does not work for right-most pdf

### ISSUE THREAD

**Issue by oliviodare** [ThomasFKJorna/zotero-night#4]
Hello @ThomasFKJorna , thank you so much! This is so great!

Little issue here, I cannot seem to get it working for the PDF itself. The UI gets dark, althought I cannot change from the two settings (`Dark` or `Matching background`), and I cannot change it back to day mode. I have to disable it to do so. The PDFs don't appear to react to the plugin.

## Specs
MacOS Monterey 12.0.1
Zotero 6.0.5-beta.5
Zotero Night [0.1.1 (Latest)](https://github.com/ThomasFKJorna/zotero-night/releases/latest).

## Some screenshots.

The plugin works fine for the UI:
<img width="500" alt="Captura de pantalla 2022-04-19 a las 16 36 27" src="https://user-images.githubusercontent.com/68588692/164031190-f79498ee-a391-4e85-89a0-c7c46ed55b79.png">

But doesn't work for the PDF's themselves:
<img width="500" alt="Captura de pantalla 2022-04-19 a las 16 36 33" src="https://user-images.githubusercontent.com/68588692/164031214-72a59b64-98fa-4c41-a313-f064763020d6.png">

And the preferences don't seem to respond either:
<img width="500" alt="Captura de pantalla 2022-04-19 a las 16 40 03" src="https://user-images.githubusercontent.com/68588692/164031244-c979b70b-88f5-47ef-ad2c-6faa29ab2f73.png">
<img width="500" alt="Captura de pantalla 2022-04-19 a las 16 40 09" src="https://user-images.githubusercontent.com/68588692/164031249-5c5f85fe-95c6-4d6a-96bc-1f1aa1af8462.png">

**Comment by ThomasFKJorna** [comment]
And the settings are only for the PDF atm, although I should really get around to making it toggleable globally, it's not that hard

**Comment by ThomasFKJorna** [comment]
It does work for me when installing through the .xpi.

**Comment by ThomasFKJorna** [comment]
Ahh I see. I'm doing something wrong with selecting the tab, try opening another one: the previous one should now work, but the rightmost does not.

**Comment by ThomasFKJorna** [comment]
@oliviodare Could you try this release? Should work better https://github.com/ThomasFKJorna/zotero-night/releases/tag/0.1.2

**Comment by oliviodare** [comment]
Okey, gotcha! It works with 0.1.2 now (with the minor issue of right-most tab not working)

**Comment by ThomasFKJorna** [comment]
Hmmm the right most tab _should_ also work

**Comment by ThomasFKJorna** [comment]
the latest version has proper loading logic and also has a global toggle, be sure to update it!

**Comment by oliviodare** [comment]
It works now, thanks!
