### ISSUE TITLE
Can not see Tags and Toolbar clearly.

### ISSUE THREAD

**Issue by CharlesChiuGit** [ThomasFKJorna/zotero-night#6]
As title. Something maybe worth mentioning is that I changed the font size in Zotero.

OS Platform: Win11 21H2
Zotero Version: 6.0.4
zotero-night: 0.2.1

Screenshots:
w/o zotero-night:
![image](https://user-images.githubusercontent.com/32497323/164105550-c709441d-188b-4bde-9c29-3bf33c6be1e0.png)

w/ zotero-night:
![image](https://user-images.githubusercontent.com/32497323/164105653-fe3c9f03-4051-4935-a1c1-35ca424dff2d.png)

**Comment by Elaborendum** [comment]
Tooltips also have a similar issue

![imagen](https://user-images.githubusercontent.com/71190696/164124851-fb799562-cf71-45ca-9150-5b16cfb3ade7.png)

**Comment by ThomasFKJorna** [comment]
The popups/toolbar issue should be slightly better in the latest release

**Comment by ThomasFKJorna** [comment]
Doing the tags later!

**Comment by CharlesChiuGit** [comment]
@ThomasFKJorna The toolbar is indeed much clearer now! Big thanks to the quick fix, much appriciate it.

**Comment by windingwind** [comment]
I also encounter this. The not selected tabs in the sidebar have bright background while the text color is in night mode.
![image](https://user-images.githubusercontent.com/33902321/165241756-1c5c90c7-6632-43fb-8eab-57bc9db53302.png)

Btw, the main window shows a scroll bar if I click somewhere in the item tree. This only happens in night mode.

**Comment by ThomasFKJorna** [comment]
> Btw, the main window shows a scroll bar if I click somewhere in the item tree. This only happens in night mode.

Huh you're right, really annoying, i'll try to fix it

**Comment by ThomasFKJorna** [comment]
<img width="653" alt="image" src="https://user-images.githubusercontent.com/21983833/165562061-238584d0-5dc8-46de-af6e-e2ad5fd70cec.png">

This is what the tags look like for me btw

**Comment by ThomasFKJorna** [comment]
The scroll thing is fixed, the menus should also be better + some other small fixes

**Comment by ThomasFKJorna** [comment]
Dang

**Comment by ThomasFKJorna** [comment]
Ah so I see that the top bar did get styled. I should figure out how to target that a bit better, but kinda difficult to do as I can't see them in MacOS, will try though!

**Comment by CharlesChiuGit** [comment]
Thank you! Feel free to dm me if you need windows testers!

**Comment by ThomasFKJorna** [comment]
Awesome, thank you! The toolbar should be a bit better now

**Comment by CharlesChiuGit** [comment]
Ys, the toolbar is fully night mode now! thank you!
![image](https://user-images.githubusercontent.com/32497323/166182554-9921f250-5c22-413d-be82-5900d3f0e132.png)

**Comment by ThomasFKJorna** [comment]
The info items etc should now be better visibel!

**Comment by CharlesChiuGit** [comment]
The tags looks super nice now! Thanks!

**Comment by windingwind** [comment]
> 我也遇到这种情况。侧边栏中未选择的选项卡具有明亮的背景，而文本颜色处于夜间模式。 ![图片](https://user-images.githubusercontent.com/33902321/165241756-1c5c90c7-6632-43fb-8eab-57bc9db53302.png)
> 
> 顺便说一句，如果我单击项目树中的某个位置，主窗口会显示一个滚动条。这仅在夜间模式下发生。

@ThomasFKJorna I have the scroll bar issue fixed. However, the code currently have some ts errors and the yarn build failed.
Any solution to solve it? I want to keep the code less edited in a PR.
